MODULE MODULE_OUTPUTUTILITY
    USE MODULE_PRECISION
    
    CONTAINS
    INTEGER FUNCTION NEWUNIT(UNIT)
      INTEGER(IP), INTENT(OUT), OPTIONAL :: UNIT
    ! LOCAL
      INTEGER(IP), PARAMETER :: LUN_MIN=10, LUN_MAX=1000
      LOGICAL :: OPENED
      INTEGER(IP) :: LUN
    ! BEGIN
      NEWUNIT=-1
      DO LUN=LUN_MIN,LUN_MAX
        INQUIRE(UNIT=LUN,OPENED=OPENED)
        IF (.NOT. OPENED) THEN
          NEWUNIT=LUN
          EXIT
        END IF
      END DO
      IF (PRESENT(UNIT)) UNIT=NEWUNIT
    END FUNCTION NEWUNIT    
END MODULE MODULE_OUTPUTUTILITY