MODULE MODULE_MATERIALCOMPONENT
    
    USE MODULE_PRECISION
    PUBLIC
    TYPE, PUBLIC    :: MATERIALCOMPONENT
    
	REAL(WP)    ::   GAMMA = 1.4_WP;
	REAL(WP)    ::   B = 1._WP;
	REAL(WP)    ::   RHO = 1.3_WP;
	REAL(WP)    ::   R_GAS_CONSTANT = 8.3144598_WP;
	REAL(WP)    ::   MU = 18.27_WP;
	REAL(WP)    ::   LAMBDA = 1.512041288_WP;
	REAL(WP)    ::   C_SUTHERLAND_CONSTANT = 120._WP;
	REAL(WP)    ::   TEMPERATURE = 291.15_WP;
    REAL(WP)    ::   PI = 3.141592654_WP
    
    CONTAINS
    
    END TYPE MATERIALCOMPONENT
    
END MODULE     MODULE_MATERIALCOMPONENT