MODULE MODULE_MODEL
    USE MODULE_ELEMENT
    USE MODULE_OUTPUTUTILITY
    
    TYPE, PUBLIC    :: MODEL
        INTEGER(IP) :: NELE
        INTEGER(IP) :: MODEL_INDEX
        INTEGER(IP) :: NBOUND
        
        TYPE(ELEMENT), DIMENSION(:), POINTER    :: ELE
        TYPE(ELEMENT), DIMENSION(:), POINTER    :: BOUND_ELE
        
        TYPE(SOLVERINFORMATION), DIMENSION(:), POINTER    :: SOLVERINFO
        
    CONTAINS
    PROCEDURE   :: MAKE => MAKE_MODEL
    PROCEDURE   :: DELETE => DELETE_MODEL
    PROCEDURE   :: OUTPUT => OUTPUT_MODEL
    END TYPE
    
    CONTAINS
    SUBROUTINE MAKE_MODEL(THIS, NELE, NVAL, LB, RB, COMSYS, MATERIALINFO, CP_COEF, DIMENSIONALINFO, SOLVERINFO)
    IMPLICIT NONE
    CLASS(MODEL), INTENT(INOUT) :: THIS
    INTEGER(IP), INTENT(IN)     :: NELE, NVAL
    REAL(WP),  INTENT(IN)       :: LB, RB
    TYPE(COMPUTATIONALSYSTEM), INTENT(IN), TARGET   :: COMSYS(:)
    TYPE(MATERIALCOMPONENT), INTENT(IN), TARGET   :: MATERIALINFO(:)
    TYPE(CORRECTIONPOLYNOMIAL), INTENT(IN), TARGET :: CP_COEF(:)
    TYPE(NONDIMENSIONALNUMBER), INTENT(IN), TARGET :: DIMENSIONALINFO(:)
    TYPE(SOLVERINFORMATION), INTENT(IN), TARGET      :: SOLVERINFO(:)
    REAL(WP)    :: DX, XL, XR
    INTEGER(IP) :: I, ORDER
    
    ALLOCATE(THIS%ELE(NELE))
    THIS%NELE = NELE
    DX = (RB - LB)/NELE
    ORDER = COMSYS(1)%ORDER
    DO I = 1, NELE
        XL = (RB - LB)*REAL(I-1, WP)/NELE + LB
        XR = (RB - LB)*REAL(I, WP)/NELE + LB
        
        CALL THIS%ELE(I)%MAKE(ORDER, NVAL, I, XL, XR, COMSYS, MATERIALINFO, CP_COEF, DIMENSIONALINFO, SOLVERINFO)
        
        ALLOCATE(THIS%BOUND_ELE(2))
        
        IF (I < NELE)   THEN 
            THIS%ELE(I)%RIGHT => THIS%ELE(I+1:I+1)
        ELSE
            THIS%ELE(I)%RIGHT => THIS%BOUND_ELE(2:2)
        END IF
        
        IF (I > 1) THEN 
            THIS%ELE(I)%LEFT => THIS%ELE(I-1:I-1)
        ELSE
            THIS%ELE(I)%LEFT => THIS%BOUND_ELE(1:1)
        END IF
        
        ! RECALCULATION DT 
        THIS%ELE(I)%SOLVERINFO%DT = THIS%ELE(I)%SOLVERINFO%CFL*DX/5._WP

    END DO
    
    THIS%SOLVERINFO => SOLVERINFO
    
    END SUBROUTINE MAKE_MODEL
    
    SUBROUTINE DELETE_MODEL(THIS)
    CLASS(MODEL), INTENT(INOUT)   :: THIS
    INTEGER(IP) :: I
    
    DO I = 1, THIS%NELE
        CALL THIS%ELE(I)%DELETE()
    END DO
    DEALLOCATE(THIS%ELE)
    THIS%NELE = 0.
    RETURN
    END SUBROUTINE DELETE_MODEL
    
    
    SUBROUTINE OUTPUT_MODEL(THIS, FILENAME)
    IMPLICIT NONE
    
    CLASS(MODEL), INTENT(INOUT) :: THIS
    CHARACTER(*), INTENT(IN)    :: FILENAME
    INTEGER(IP) :: IUNIT, IELE, N, J, IORDER, NVAL, IVAL
    
    IUNIT = NEWUNIT()
    
    OPEN(UNIT = IUNIT, FILE = TRIM(FILENAME), ACTION = "WRITE")
    DO IELE = 1, THIS%NELE, 1
        N = THIS%ELE(IELE)%ORDER + 1
        NVAL = THIS%ELE(IELE)%NVAL
        DO IORDER = 1, N
            WRITE(IUNIT, 10,ADVANCE = 'NO') " ", THIS%ELE(IELE)%XK(IORDER)
            DO IVAL = 1, NVAL
                WRITE(IUNIT, 10,ADVANCE = 'NO') "  ", THIS%ELE(IELE)%CONSERVATIVE(IORDER, IVAL)
            END DO
            DO IVAL = 1, NVAL
                WRITE(IUNIT, 10, ADVANCE = 'NO') " ", THIS%ELE(IELE)%PRIMATIVE(IORDER, IVAL)
            END DO
            WRITE(IUNIT, *) " "
        END DO
    END DO
    
    
    CLOSE(UNIT = IUNIT)
10  FORMAT(A4, F30.10)    
    END SUBROUTINE OUTPUT_MODEL
END MODULE MODULE_MODEL    