MODULE MODULE_PRECISION
    
    USE, INTRINSIC  :: ISO_FORTRAN_ENV
    USE, INTRINSIC  :: IEEE_ARITHMETIC, ONLY : IEEE_IS_FINITE
    
    IMPLICIT NONE
    
    INTEGER, PARAMETER  :: SP = REAL32
    INTEGER, PARAMETER  :: DP = REAL64
    
    INTEGER, PARAMETER  :: WP = DP
    INTEGER, PARAMETER  :: IP = SELECTED_INT_KIND(8)
END MODULE MODULE_PRECISION    